core:
  ai_provider: openai
  branch: main
  poll_interval: 300
  repo_path: C:\\Users\\developer\\Documents\\workspace\\wekall\\chatcenter-we
modules:
  AIAnalyzer:
    enabled: true
    openai_model: gpt-3.5-turbo
    temperature: 0
    verbose: true
  CodeReviewer:
    enabled: true
    review_types:
    - python
    - javascript
    - typescript
    severity_threshold: low
    suggest_fixes: true
    use_ai: true
  CommitMessageGenerator:
    analyze_content: true
    convention: custom
    custom_template: '{type}: {message}'
    enabled: true
    include_body: true
    include_footer: false
    include_scope: false
    language: english
    max_length: '72'
    summarize_changes: true
    use_ai: true
  DocstringGenerator:
    enabled: true
    format: google
    languages:
    - python
    - javascript
    - typescript
    use_ai: true
  ImpactAnalyzer:
    analyze_dependencies: true
    enabled: true
    risk_threshold: medium
    suggest_tests: true
    use_ai: true
