core:
  ai_provider: openai
  branch: master
  poll_interval: 300
  repo_path: .
modules:
  CodeReviewer:
    enabled: true
    review_types:
    - quality
    - security
    - performance
    severity_threshold: low
    suggest_fixes: true
  CommitMessageGenerator:
    convention: conventional
    custom_template: '{type}: {message}'
    enabled: true
    include_body: true
    include_footer: false
    include_scope: true
    language: english
    max_length: '72'
  DocstringGenerator:
    enabled: true
    format: google
    languages:
    - python
    - javascript
  ImpactAnalyzer:
    analyze_dependencies: true
    enabled: true
    risk_threshold: medium
    suggest_tests: true
